<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>GeosBeltTweaks</AssemblyName>
    <RootNamespace>GeosBeltTweaks</RootNamespace>
    <Product>Geo's Belt Tweaks</Product>
    <Description>Geo's belt tweaks for Dyson Sphere Program</Description>
    <BepInExPluginGuid>com.geostyx.dsp.geosbelttweaks</BepInExPluginGuid>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.17" ExcludeAssets="runtime" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" PrivateAssets="all" />
    <PackageReference Include="DysonSphereProgram.GameLibs" Version="0.10.35.29088-r.0" IncludeAssets="compile" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

</Project>
